runtime: python39  
entrypoint: python -B main.py

instance_class: F1 

env_variables:
  PYTHONUNBUFFERED: "1"

automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10 